name: Run tests with coverage
env:
  version: 9.0.0

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:

  test-coverage:
    runs-on: macos-14
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (SCIPOptSuite)
        run: |
          wget --quiet --no-check-certificate https://github.com/scipopt/scip/releases/download/$(echo "v${{env.version}}" | tr -d '.')/SCIP-${{ env.version }}-Darwin-arm.zip -O scip.zip
          unzip scip.zip

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare python environment
        run: |
          export SCIPOPTDIR=$(pwd)/scip_install
          python -m pip install --upgrade pip
          python -m pip install networkx cython pytest-cov

      - name: Install PySCIPOpt
        run: python -m pip install .

      - name: Run pyscipopt tests
        run: |
          coverage run -m pytest
          coverage report -m
          coverage xml
      
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
